const SUBJECTS = {
  // ── 교육학 ──
  "교육과정론": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-curriculum-bg)", mid:"var(--c-edu-curriculum-mid)", accent:"var(--c-edu-curriculum-accent)", text:"var(--c-edu-curriculum-text)" }
  },
  "교육심리학": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-psych-bg)", mid:"var(--c-edu-psych-mid)", accent:"var(--c-edu-psych-accent)", text:"var(--c-edu-psych-text)" }
  },
  "교수학습이론": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-teach-bg)", mid:"var(--c-edu-teach-mid)", accent:"var(--c-edu-teach-accent)", text:"var(--c-edu-teach-text)" }
  },
  "교육평가론": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-eval-bg)", mid:"var(--c-edu-eval-mid)", accent:"var(--c-edu-eval-accent)", text:"var(--c-edu-eval-text)" }
  },
  "교육행정": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-admin-bg)", mid:"var(--c-edu-admin-mid)", accent:"var(--c-edu-admin-accent)", text:"var(--c-edu-admin-text)" }
  },
  "생활지도·상담": {
    area: "교육학", areaKey: "edu",
    color: { bg:"var(--c-edu-counsel-bg)", mid:"var(--c-edu-counsel-mid)", accent:"var(--c-edu-counsel-accent)", text:"var(--c-edu-counsel-text)" }
  },
  // ── 전공 CS ──
  "자료구조": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-ds-bg)", mid:"var(--c-cs-ds-mid)", accent:"var(--c-cs-ds-accent)", text:"var(--c-cs-ds-text)" }
  },
  "알고리즘": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-algo-bg)", mid:"var(--c-cs-algo-mid)", accent:"var(--c-cs-algo-accent)", text:"var(--c-cs-algo-text)" }
  },
  "운영체제": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-os-bg)", mid:"var(--c-cs-os-mid)", accent:"var(--c-cs-os-accent)", text:"var(--c-cs-os-text)" }
  },
  "컴퓨터 구조": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-arch-bg)", mid:"var(--c-cs-arch-mid)", accent:"var(--c-cs-arch-accent)", text:"var(--c-cs-arch-text)" }
  },
  "데이터베이스": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-db-bg)", mid:"var(--c-cs-db-mid)", accent:"var(--c-cs-db-accent)", text:"var(--c-cs-db-text)" }
  },
  "네트워크": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-net-bg)", mid:"var(--c-cs-net-mid)", accent:"var(--c-cs-net-accent)", text:"var(--c-cs-net-text)" }
  },
  "프로그래밍 언어론": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-pl-bg)", mid:"var(--c-cs-pl-mid)", accent:"var(--c-cs-pl-accent)", text:"var(--c-cs-pl-text)" }
  },
  "소프트웨어공학": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-se-bg)", mid:"var(--c-cs-se-mid)", accent:"var(--c-cs-se-accent)", text:"var(--c-cs-se-text)" }
  },
  "이산수학": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-discrete-bg)", mid:"var(--c-cs-discrete-mid)", accent:"var(--c-cs-discrete-accent)", text:"var(--c-cs-discrete-text)" }
  },
  "컴파일러": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-compiler-bg)", mid:"var(--c-cs-compiler-mid)", accent:"var(--c-cs-compiler-accent)", text:"var(--c-cs-compiler-text)" }
  },
  "인공지능": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-ai-bg)", mid:"var(--c-cs-ai-mid)", accent:"var(--c-cs-ai-accent)", text:"var(--c-cs-ai-text)" }
  },
  "정보보안": {
    area: "전공", areaKey: "cs",
    color: { bg:"var(--c-cs-sec-bg)", mid:"var(--c-cs-sec-mid)", accent:"var(--c-cs-sec-accent)", text:"var(--c-cs-sec-text)" }
  },
  // ── 전공 정보교육 ──
  "컴퓨팅 사고력(CT)": {
    area: "교과교육학", areaKey: "info",
    color: { bg:"var(--c-info-ct-bg)", mid:"var(--c-info-ct-mid)", accent:"var(--c-info-ct-accent)", text:"var(--c-info-ct-text)" }
  },
  "정보과 교육과정": {
    area: "교과교육학", areaKey: "info",
    color: { bg:"var(--c-info-curriculum-bg)", mid:"var(--c-info-curriculum-mid)", accent:"var(--c-info-curriculum-accent)", text:"var(--c-info-curriculum-text)" }
  },
  "교수학습 방법": {
    area: "교과교육학", areaKey: "info",
    color: { bg:"var(--c-info-teach-bg)", mid:"var(--c-info-teach-mid)", accent:"var(--c-info-teach-accent)", text:"var(--c-info-teach-text)" }
  },
  "SW·AI 교육론": {
    area: "교과교육학", areaKey: "info",
    color: { bg:"var(--c-info-swai-bg)", mid:"var(--c-info-swai-mid)", accent:"var(--c-info-swai-accent)", text:"var(--c-info-swai-text)" }
  },
  "평가론": {
    area: "교과교육학", areaKey: "info",
    color: { bg:"var(--c-info-eval-bg)", mid:"var(--c-info-eval-mid)", accent:"var(--c-info-eval-accent)", text:"var(--c-info-eval-text)" }
  }
};

const CONCEPTS = [
  // ══ 교육과정론 ══
  {subject:"교육과정론",chapter:"교육과정 이론",name:"타일러 목표중심 모형",keywords:"행동목표·학습경험선정·조직·평가",freq:"높음",viz:true,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 이론",name:"브루너 나선형 교육과정",keywords:"지식구조·발견학습·나선형 반복",freq:"높음",viz:true,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 이론",name:"아이즈너 예술적 교육과정",keywords:"표현적 목표·교육적 감식안·질적평가",freq:"중간",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 이론",name:"워커 자연주의적 모형",keywords:"강령·숙의·설계·실천적 절충",freq:"중간",viz:true,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 이론",name:"위긴스·맥타이 백워드 설계",keywords:"바람직한결과→증거→학습계획",freq:"중간",viz:true,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 이론",name:"슈왑 실제적 교육과정",keywords:"실천·숙의·교사전문성",freq:"낮음",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"교과중심 교육과정",keywords:"분과형·상관형·융합형",freq:"중간",viz:true,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"경험중심 교육과정",keywords:"아동중심·흥미·활동 중심",freq:"중간",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"학문중심 교육과정",keywords:"지식의 구조·탐구학습·브루너",freq:"중간",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"인간중심 교육과정",keywords:"자아실현·정의적 목표·전인교육",freq:"낮음",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"잠재적 교육과정",keywords:"잭슨·비의도적 학습·학교문화",freq:"높음",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 유형",name:"영 교육과정",keywords:"아이즈너·가르치지 않는 것",freq:"중간",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 개발",name:"중앙집권형 vs 지방분권형",keywords:"국가주도·교사참여·자율성",freq:"중간",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 개발",name:"2022 개정 교육과정 총론",keywords:"역량기반·고교학점제·미래교육",freq:"높음",viz:false,quiz:true},
  {subject:"교육과정론",chapter:"교육과정 개발",name:"성취기준 분석·재구성 (교육과정론)",keywords:"교과통합·성취기준 재구성 방법",freq:"높음",viz:false,quiz:true},
  // ══ 교육심리학 ══
  {subject:"교육심리학",chapter:"발달이론",name:"피아제 인지발달 4단계",keywords:"감각운동·전조작·구체적조작·형식적조작",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"피아제 핵심개념",keywords:"도식·동화·조절·평형화",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"비고츠키 ZPD·비계설정",keywords:"근접발달영역·비계·더유능한타자",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"비고츠키 언어와 사고",keywords:"혼잣말·내적언어·사회적언어",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"에릭슨 심리사회 발달 8단계",keywords:"신뢰감·자율성·주도성·근면성·정체성",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"콜버그 도덕발달 3수준 6단계",keywords:"인습전·인습·인습후·딜레마",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"길리건 배려윤리",keywords:"콜버그 비판·관계중심·여성발달",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"프로이트 심리성적 발달",keywords:"구강기·항문기·남근기·잠복기·생식기",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"마르시아 정체성 지위",keywords:"정체감 혼미·유실·유예·성취",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"발달이론",name:"브론펜브레너 생태학적 체계",keywords:"미시·중간·외체계·거시·시간체계",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"매슬로 욕구위계 5단계",keywords:"생리·안전·소속·존중·자아실현",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"반두라 자기효능감",keywords:"4가지 원천·관찰학습·대리경험",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"반두라 사회인지이론",keywords:"상호결정론·자기조절·모델링",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"드웩 성장 마인드셋",keywords:"고정형·성장형 지능관·귀인",freq:"높음",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"와이너 귀인이론",keywords:"능력·노력·과제난이도·운·소재·안정성",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"데시·라이언 자기결정이론",keywords:"내재동기·외재동기·자율성·유능감·관계성",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"성취목표이론",keywords:"숙달목표·수행접근목표·수행회피목표",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"동기이론",name:"기대×가치 이론",keywords:"기대신념·주관적과제가치·에클스",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"파블로프 고전적 조건화",keywords:"조건자극·무조건반응·소거·자발적회복",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"손다이크 시행착오설",keywords:"효과의 법칙·연습의 법칙·준비의 법칙",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"스키너 조작적 조건화",keywords:"정적강화·부적강화·처벌·소거·강화계획",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"강화계획 유형",keywords:"고정비율·변동비율·고정간격·변동간격",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"오수벨 유의미 수용학습",keywords:"선행조직자·포섭·동화·파지",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"가네 학습의 위계",keywords:"지적기능·인지전략·언어정보·운동기능·태도",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"학습이론",name:"관찰학습(모델링)",keywords:"주의·파지·재생·동기화 4단계",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"정보처리이론 모델",keywords:"감각기억·작업기억·장기기억·주의",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"작업기억의 구조",keywords:"음운루프·시공간메모장·중앙집행기·일화완충기",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"장기기억 유형",keywords:"서술기억(의미·일화)·절차기억·암묵기억",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"망각이론",keywords:"소멸설·간섭설·인출실패설·동기적망각",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"메타인지",keywords:"인지에 대한 인지·자기조절·플라벨",freq:"높음",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"인지·기억",name:"전이",keywords:"정적/부적전이·근전이·원전이·일반화",freq:"중간",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"개인차",name:"지능이론 — 스피어만·가드너",keywords:"g요인·다중지능 8가지",freq:"높음",viz:true,quiz:true},
  {subject:"교육심리학",chapter:"개인차",name:"지능이론 — 스턴버그",keywords:"삼원지능·분석적·창의적·실용적",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"개인차",name:"창의성",keywords:"수렴적·확산적 사고·길포드·창의성 신장",freq:"중간",viz:false,quiz:true},
  {subject:"교육심리학",chapter:"개인차",name:"학습양식",keywords:"시각형·청각형·운동형·콜브 경험학습",freq:"낮음",viz:false,quiz:true},
  // ══ 교수학습이론 ══
  {subject:"교수학습이론",chapter:"교수설계",name:"가네 9가지 수업사태",keywords:"주의획득·목표제시·선행학습자극 등",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습이론",chapter:"교수설계",name:"켈러 ARCS 동기설계",keywords:"주의·관련성·자신감·만족감",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습이론",chapter:"교수설계",name:"딕·캐리 체제적 교수설계",keywords:"ISD 10단계·형성평가·수정",freq:"중간",viz:true,quiz:true},
  {subject:"교수학습이론",chapter:"교수설계",name:"메릴 내용요소제시이론",keywords:"내용유형·수행수준·일차/이차제시형",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수설계",name:"라이겔루스 정교화이론",keywords:"정교화계열·선수학습·요약자·비유자",freq:"낮음",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수설계",name:"백워드 설계(위긴스)",keywords:"이해중심 교육과정·본질적 질문·수행과제",freq:"중간",viz:true,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"강의법·토의법",keywords:"장단점·적용상황·질문기술",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"협동학습 — STAD·직소",keywords:"긍정적 상호의존·개별책임·동등참여",freq:"높음",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"협동학습 — TGT·GI",keywords:"팀게임토너먼트·집단조사",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"문제기반학습 (PBL)",keywords:"비구조화문제·자기주도·메타인지",freq:"높음",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"프로젝트 학습",keywords:"실제적 과제·산출물·협력·발표",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"플립러닝",keywords:"사전영상·심화활동·역전학습",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"직접교수법",keywords:"모델링·안내연습·독립연습",freq:"중간",viz:true,quiz:true},
  {subject:"교수학습이론",chapter:"교수방법",name:"발견학습·탐구학습",keywords:"귀납적·가설검증·과학적사고",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"구성주의",name:"인지적 구성주의(피아제)",keywords:"개인내적구성·동화조절·발달의인식론",freq:"높음",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"구성주의",name:"사회적 구성주의(비고츠키)",keywords:"사회적상호작용·ZPD·언어매개",freq:"높음",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"구성주의",name:"상황학습·인지적도제",keywords:"실제맥락·코칭·발판·명료화",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습이론",chapter:"구성주의",name:"앵커드 교수법",keywords:"실제상황 닻 내리기·영상기반·재스퍼시리즈",freq:"낮음",viz:false,quiz:true},
  // ══ 교육평가론 ══
  {subject:"교육평가론",chapter:"평가 기초",name:"타당도 유형",keywords:"내용·구인·공인·예언 타당도",freq:"높음",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 기초",name:"신뢰도 유형",keywords:"검사재검사·동형검사·반분검사·내적합치도",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"평가 기초",name:"객관도·실용도",keywords:"채점자간 일치도·실시·채점·해석 용이성",freq:"중간",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 기초",name:"타당도-신뢰도 관계",keywords:"신뢰도는 타당도의 필요조건",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"평가 기준",name:"규준지향평가 (상대평가)",keywords:"정규분포가정·석차·백분위·표준점수",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"평가 기준",name:"준거지향평가 (절대평가)",keywords:"숙달기준·최소능력·합격불합격",freq:"높음",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 기준",name:"능력지향·성장지향평가",keywords:"개인내차·성장변화 측정",freq:"중간",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 시기",name:"진단·형성·총괄평가",keywords:"목적·시기·활용방법",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"평가 시기",name:"과정중심평가",keywords:"학습을위한평가·수행중관찰·피드백",freq:"높음",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 유형",name:"수행평가",keywords:"직접수행·포트폴리오·관찰·면접",freq:"높음",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 유형",name:"포트폴리오 평가",keywords:"수집·선택·반성·학습과정 기록",freq:"중간",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"평가 유형",name:"진정성 평가",keywords:"실제적과제·실생활맥락·복합능력",freq:"중간",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"문항 제작",name:"선택형 문항 제작",keywords:"지시문·답지구성·오답매력도",freq:"중간",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"문항 제작",name:"서답형·논술형 문항",keywords:"채점기준·루브릭·예시답안",freq:"높음",viz:false,quiz:true},
  {subject:"교육평가론",chapter:"문항 분석",name:"문항난이도·변별도",keywords:"고전검사이론·P값·D값",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"문항 분석",name:"문항반응이론 (IRT)",keywords:"1모수·2모수·3모수 모형·문항특성곡선",freq:"중간",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"점수 해석",name:"원점수·표준점수",keywords:"Z점수·T점수·스태나인·백분위",freq:"높음",viz:true,quiz:true},
  {subject:"교육평가론",chapter:"점수 해석",name:"정규분포와 평가",keywords:"표준편차·정규분포곡선·점수분포",freq:"높음",viz:true,quiz:true},
  // ══ 교육행정 ══
  {subject:"교육행정",chapter:"조직이론",name:"관료제 이론 (베버)",keywords:"합리적합법적 권위·규칙·위계",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"조직이론",name:"학교조직의 특수성",keywords:"전문적관료제·이완결합·조직화된무정부",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"조직이론",name:"학습조직",keywords:"공유비전·팀학습·시스템사고·센게",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"동기이론(행정)",name:"매슬로·허즈버그 동기위생이론",keywords:"위생요인·동기요인·2요인이론",freq:"높음",viz:true,quiz:true},
  {subject:"교육행정",chapter:"동기이론(행정)",name:"맥그리거 XY이론",keywords:"X이론(통제)·Y이론(자율)·관리방식",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"동기이론(행정)",name:"브룸 기대이론",keywords:"기대·수단성·유의성·동기력",freq:"중간",viz:true,quiz:true},
  {subject:"교육행정",chapter:"리더십",name:"특성론·행동론·상황론",keywords:"리더십발달단계·피들러·허시블랜차드",freq:"중간",viz:true,quiz:true},
  {subject:"교육행정",chapter:"리더십",name:"변혁적·거래적 리더십",keywords:"번스·바스·카리스마·개별화배려",freq:"높음",viz:true,quiz:true},
  {subject:"교육행정",chapter:"리더십",name:"분산적·서번트 리더십",keywords:"공유리더십·봉사·임파워먼트",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"의사소통·갈등",name:"의사소통 유형·장애",keywords:"공식·비공식·상향·하향·수평",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"의사소통·갈등",name:"갈등관리 전략",keywords:"회피·경쟁·타협·협력·수용",freq:"중간",viz:true,quiz:true},
  {subject:"교육행정",chapter:"장학",name:"장학의 유형",keywords:"임상·동료·자기·약식·컨설팅 장학",freq:"높음",viz:false,quiz:true},
  {subject:"교육행정",chapter:"장학",name:"수업장학 과정",keywords:"관찰전협의·수업관찰·관찰후협의",freq:"중간",viz:true,quiz:true},
  {subject:"교육행정",chapter:"교육법규",name:"교육기본법·초중등교육법",keywords:"학생인권·교원지위·학교운영위원회",freq:"중간",viz:false,quiz:true},
  {subject:"교육행정",chapter:"교육법규",name:"교원 임용·평가 제도",keywords:"교원능력개발평가·성과급·승진",freq:"중간",viz:false,quiz:true},
  // ══ 생활지도·상담 ══
  {subject:"생활지도·상담",chapter:"상담이론",name:"정신분석 상담 (프로이트)",keywords:"방어기제·전이·역전이·자유연상",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"아들러 개인심리학",keywords:"열등감·보상·생활양식·사회적관심",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"로저스 인간중심상담",keywords:"무조건적 긍정적 존중·공감·진솔성",freq:"높음",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"엘리스 REBT",keywords:"비합리적신념·ABC모델·논박·효과",freq:"높음",viz:true,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"벡 인지치료",keywords:"자동적사고·인지왜곡·인지재구조화",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"글래서 현실치료·WDEP",keywords:"선택이론·현재행동·욕구충족",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"행동주의 상담",keywords:"체계적둔감법·이완훈련·강화",freq:"중간",viz:true,quiz:true},
  {subject:"생활지도·상담",chapter:"상담이론",name:"게슈탈트 상담 (펄스)",keywords:"지금여기·알아차림·미해결과제",freq:"낮음",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"진로이론",name:"홀랜드 직업적 성격유형",keywords:"RIASEC·일치성·차별성·일관성",freq:"높음",viz:true,quiz:true},
  {subject:"생활지도·상담",chapter:"진로이론",name:"슈퍼 진로발달이론",keywords:"생애단계·직업자아개념·생애역할",freq:"높음",viz:true,quiz:true},
  {subject:"생활지도·상담",chapter:"진로이론",name:"크럼볼츠 사회학습진로이론",keywords:"학습경험·계획된우연·우연활용기술",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"진로이론",name:"고트프레드슨 제한타협이론",keywords:"성적 적합성·사회적 위신·포부타협",freq:"낮음",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"집단상담",name:"집단상담 발달단계",keywords:"초기·과도기·작업·종결단계",freq:"중간",viz:true,quiz:true},
  {subject:"생활지도·상담",chapter:"집단상담",name:"집단상담 기법",keywords:"공감·직면·자기노출·즉시성·해석",freq:"중간",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"위기개입",name:"학교폭력 예방·개입",keywords:"학교폭력예방법·위기개입절차",freq:"높음",viz:false,quiz:true},
  {subject:"생활지도·상담",chapter:"위기개입",name:"자살예방 게이트키퍼",keywords:"QPR·위기신호·개입방법",freq:"중간",viz:false,quiz:true},
  // ══ 자료구조 ══
  {subject:"자료구조",chapter:"선형구조",name:"배열·동적배열",keywords:"정적배열·ArrayList·시간복잡도",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"선형구조",name:"단순·이중·원형 연결리스트",keywords:"노드·포인터·삽입·삭제",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"선형구조",name:"스택",keywords:"LIFO·push·pop·괄호검사·후위표기법",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"선형구조",name:"큐·덱·원형큐",keywords:"FIFO·enqueue·dequeue·순환구조",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"선형구조",name:"우선순위 큐",keywords:"힙기반·삽입·삭제·O(logn)",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"이진트리 개념·성질",keywords:"포화·완전·편향이진트리",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"이진트리 순회",keywords:"전위·중위·후위·레벨순서",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"이진탐색트리 (BST)",keywords:"삽입·탐색·삭제·균형·O(logn)~O(n)",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"AVL트리·레드블랙트리",keywords:"자가균형·회전·O(logn) 보장",freq:"중간",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"힙 (Heap)",keywords:"최대힙·최소힙·heapify·힙정렬",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"B트리·B+트리",keywords:"다진트리·디스크기반·인덱스",freq:"중간",viz:true,quiz:true},
  {subject:"자료구조",chapter:"트리",name:"트라이 (Trie)",keywords:"문자열검색·접두사트리·자동완성",freq:"중간",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"그래프 개념·표현",keywords:"방향/무방향·인접행렬·인접리스트",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"DFS (깊이우선탐색)",keywords:"재귀·스택·방문순서·복잡도",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"BFS (너비우선탐색)",keywords:"큐·레벨탐색·최단경로·복잡도",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"최소신장트리 — 크루스칼·프림",keywords:"그리디·유니온파인드·간선정렬",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"최단경로 — 다익스트라",keywords:"우선순위큐·음수간선불가·O(ElogV)",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"최단경로 — 벨만포드·플로이드",keywords:"음수간선·전쌍최단경로·DP",freq:"중간",viz:true,quiz:true},
  {subject:"자료구조",chapter:"그래프",name:"위상정렬",keywords:"DAG·진입차수·작업순서",freq:"중간",viz:true,quiz:true},
  {subject:"자료구조",chapter:"해시",name:"해시함수·해시테이블",keywords:"나머지·폴딩·중간제곱법",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"해시",name:"충돌처리 — 체이닝·개방주소법",keywords:"선형조사·이중해싱·부하율",freq:"높음",viz:true,quiz:true},
  // ══ 알고리즘 ══
  {subject:"알고리즘",chapter:"정렬",name:"버블·선택·삽입 정렬",keywords:"O(n²)·안정성·구현",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"정렬",name:"합병 정렬",keywords:"분할정복·안정·O(nlogn)·공간O(n)",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"정렬",name:"퀵 정렬",keywords:"피벗·파티션·평균O(nlogn)·최악O(n²)",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"정렬",name:"힙 정렬",keywords:"힙이용·O(nlogn)·불안정·제자리",freq:"중간",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"정렬",name:"기수·계수·버킷 정렬",keywords:"비교기반X·O(n)·조건부",freq:"중간",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"탐색",name:"선형탐색·이진탐색",keywords:"O(n)·O(logn)·전제조건",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"탐색",name:"보간탐색·피보나치탐색",keywords:"이진탐색 변형·특수조건",freq:"낮음",viz:false,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"동적 프로그래밍 (DP)",keywords:"최적부분구조·중복부분문제·메모이제이션",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"DP 대표 문제",keywords:"LCS·LIS·배낭문제·행렬연쇄곱셈",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"그리디 알고리즘",keywords:"탐욕선택·최적부분구조·활동선택",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"분할정복",keywords:"재귀·병합정렬·퀵정렬·카라츠바",freq:"중간",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"백트래킹",keywords:"상태공간트리·가지치기·N퀸",freq:"중간",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"알고리즘 기법",name:"문자열 탐색 — KMP·보이어무어",keywords:"실패함수·패턴매칭·O(n+m)",freq:"중간",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"복잡도",name:"시간·공간 복잡도 분석",keywords:"Big-O·Ω·Θ·최선/평균/최악 구분",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"복잡도",name:"P·NP·NP완전",keywords:"결정문제·다항시간·환원",freq:"중간",viz:true,quiz:true},
  // ══ 운영체제 ══
  {subject:"운영체제",chapter:"프로세스",name:"프로세스 개념·상태",keywords:"생성·준비·실행·대기·종료·PCB",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"프로세스",name:"프로세스 vs 스레드",keywords:"PCB·TCB·멀티스레딩·공유자원",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"프로세스",name:"프로세스 생성·종료",keywords:"fork·exec·wait·좀비·고아",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"프로세스",name:"문맥교환 (Context Switch)",keywords:"PCB저장·복원·오버헤드",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"CPU 스케줄링",name:"FCFS·SJF·SRTF",keywords:"비선점·선점·호위효과·기아",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"CPU 스케줄링",name:"라운드로빈·우선순위",keywords:"시간할당량·타임아웃·에이징",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"CPU 스케줄링",name:"다단계큐·다단계피드백큐",keywords:"큐분리·피드백·동적우선순위",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"동기화",name:"경쟁조건·임계구역 문제",keywords:"상호배제·진행·한정대기 조건",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"동기화",name:"뮤텍스·세마포어",keywords:"이진세마포어·계수세마포어·P·V연산",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"동기화",name:"모니터",keywords:"고수준동기화·condition variable·자바synchronized",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"동기화",name:"고전 동기화 문제",keywords:"생산자소비자·독자저자·식사철학자",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"교착상태",name:"교착상태 4가지 필요조건",keywords:"상호배제·점유대기·비선점·순환대기",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"교착상태",name:"교착상태 처리 — 예방·회피",keywords:"자원할당거부·은행원알고리즘",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"교착상태",name:"교착상태 처리 — 탐지·회복",keywords:"자원할당그래프·프로세스종료·자원선점",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"메모리 관리",name:"연속할당·단편화",keywords:"고정분할·가변분할·내부/외부단편화",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"메모리 관리",name:"페이징",keywords:"페이지테이블·TLB·논리/물리주소변환",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"메모리 관리",name:"세그멘테이션",keywords:"세그먼트테이블·세그먼트번호·오프셋",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"가상 메모리",name:"요구 페이징·페이지폴트",keywords:"페이지폴트처리·스왑인아웃",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"가상 메모리",name:"페이지 교체 알고리즘",keywords:"FIFO·OPT·LRU·LFU·클락",freq:"높음",viz:true,quiz:true},
  {subject:"운영체제",chapter:"가상 메모리",name:"스래싱·워킹셋",keywords:"스래싱원인·워킹셋모델·PFF",freq:"중간",viz:true,quiz:true},
  {subject:"운영체제",chapter:"파일시스템",name:"파일·디렉터리 구조",keywords:"inode·FAT·디렉터리엔트리",freq:"중간",viz:false,quiz:true},
  {subject:"운영체제",chapter:"파일시스템",name:"디스크 스케줄링",keywords:"FCFS·SSTF·SCAN·C-SCAN·LOOK",freq:"중간",viz:true,quiz:true},
  // ══ 컴퓨터 구조 ══
  {subject:"컴퓨터 구조",chapter:"디지털 논리",name:"부울대수·논리게이트",keywords:"AND·OR·NOT·NAND·NOR·XOR",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"디지털 논리",name:"조합회로·순서회로",keywords:"가산기·멀티플렉서·플립플롭·레지스터",freq:"중간",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"데이터 표현",name:"수의 표현·진법변환",keywords:"2진수·8진수·16진수·BCD",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"데이터 표현",name:"정수 표현 — 보수",keywords:"1의보수·2의보수·부호절대값",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"데이터 표현",name:"부동소수점 (IEEE 754)",keywords:"단정도·배정도·지수·가수·정밀도",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"CPU 구조",name:"CPU 구성요소",keywords:"ALU·레지스터·제어장치·내부버스",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"CPU 구조",name:"명령어 사이클",keywords:"인출·해독·실행·메모리접근·저장",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"CPU 구조",name:"명령어 형식·주소지정",keywords:"즉시·직접·간접·레지스터·상대주소",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"CPU 구조",name:"RISC vs CISC",keywords:"명령어집합·파이프라인적합성",freq:"중간",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"파이프라인",name:"파이프라인 개념·단계",keywords:"IF·ID·EX·MEM·WB 5단계",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"파이프라인",name:"파이프라인 해저드",keywords:"구조적·데이터·제어 해저드·해결방법",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"파이프라인",name:"슈퍼스칼라·명령어수준병렬성",keywords:"ILP·비순서실행·분기예측",freq:"중간",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"메모리 계층",name:"메모리 계층구조",keywords:"레지스터→캐시→RAM→SSD→HDD",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"메모리 계층",name:"캐시 메모리",keywords:"지역성원리·직접/연관/집합연관 매핑",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"메모리 계층",name:"캐시 교체정책·쓰기정책",keywords:"LRU·LFU·랜덤·write-through·write-back",freq:"중간",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"입출력",name:"I/O 방식",keywords:"프로그램I/O·인터럽트구동·DMA",freq:"중간",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"입출력",name:"버스 구조",keywords:"데이터버스·주소버스·제어버스·버스중재",freq:"중간",viz:false,quiz:true},
  // ══ 데이터베이스 ══
  {subject:"데이터베이스",chapter:"관계형 모델",name:"관계형 데이터 모델",keywords:"릴레이션·튜플·속성·도메인",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"관계형 모델",name:"키의 종류",keywords:"기본키·외래키·후보키·대리키·슈퍼키",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"관계형 모델",name:"무결성 제약조건",keywords:"개체무결성·참조무결성·도메인무결성",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"관계형 모델",name:"관계 대수",keywords:"선택·투영·조인·합집합·차집합·교집합",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"SQL",name:"DDL·DML·DCL·TCL",keywords:"CREATE·SELECT·GRANT·COMMIT 구분",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"SQL",name:"SQL 조인 유형",keywords:"INNER·LEFT·RIGHT·FULL·CROSS JOIN",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"SQL",name:"서브쿼리·집계함수",keywords:"IN·EXISTS·GROUP BY·HAVING",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"SQL",name:"뷰·인덱스",keywords:"뷰생성·인덱스구조·클러스터드·논클러스터드",freq:"중간",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"DB 설계",name:"ER 모델·ER다이어그램",keywords:"개체·관계·속성·카디널리티·참여도",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"DB 설계",name:"정규화 — 1NF·2NF·3NF",keywords:"이상현상·함수적종속·부분/이행종속",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"DB 설계",name:"정규화 — BCNF·4NF·5NF",keywords:"결정자·후보키·다치종속",freq:"중간",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"DB 설계",name:"역정규화",keywords:"성능향상·조인감소·중복허용",freq:"중간",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"트랜잭션",name:"트랜잭션 개념·ACID",keywords:"원자성·일관성·고립성·지속성",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"트랜잭션",name:"동시성 제어 — 락",keywords:"공유락·배타락·2단계 락킹 프로토콜",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"트랜잭션",name:"동시성 제어 — 타임스탬프",keywords:"타임스탬프 순서화·낙관적 동시성제어",freq:"중간",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"트랜잭션",name:"회복 기법",keywords:"로그기반·체크포인트·REDO·UNDO",freq:"중간",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"트랜잭션",name:"이상현상",keywords:"갱신손실·더티리드·반복불가능·팬텀리드",freq:"높음",viz:true,quiz:true},
  // ══ 네트워크 ══
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"OSI 7계층 역할·PDU",keywords:"물데네전세표응·프레임·패킷·세그먼트",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"TCP/IP 4계층",keywords:"네트워크접속·인터넷·전송·응용",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"TCP 특성·흐름제어",keywords:"슬라이딩윈도우·혼잡제어·3-way·4-way",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"UDP 특성·활용",keywords:"비연결·비신뢰·DNS·DHCP·스트리밍",freq:"높음",viz:false,quiz:true},
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"TCP 3-way handshake",keywords:"SYN·SYN-ACK·ACK·연결설정",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"OSI·TCP/IP",name:"TCP 혼잡제어",keywords:"슬로우스타트·혼잡회피·빠른재전송",freq:"중간",viz:true,quiz:true},
  {subject:"네트워크",chapter:"IP·주소",name:"IPv4 주소 체계",keywords:"클래스·서브넷·브로드캐스트·네트워크주소",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"IP·주소",name:"서브넷팅·CIDR",keywords:"서브넷마스크·VLSM·슈퍼네팅",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"IP·주소",name:"IPv6",keywords:"128비트·헤더단순화·자동설정·전환",freq:"중간",viz:false,quiz:true},
  {subject:"네트워크",chapter:"IP·주소",name:"NAT·DHCP",keywords:"사설IP·주소변환·동적할당",freq:"중간",viz:false,quiz:true},
  {subject:"네트워크",chapter:"라우팅",name:"라우팅 개념·라우팅테이블",keywords:"정적·동적라우팅·라우팅테이블구조",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"라우팅",name:"거리벡터 — RIP",keywords:"벨만포드·홉수·무한루프·분할수평선",freq:"중간",viz:true,quiz:true},
  {subject:"네트워크",chapter:"라우팅",name:"링크상태 — OSPF",keywords:"다익스트라·링크상태데이터베이스·Area",freq:"중간",viz:true,quiz:true},
  {subject:"네트워크",chapter:"라우팅",name:"BGP (외부 라우팅)",keywords:"AS간라우팅·경로벡터·인터넷백본",freq:"낮음",viz:false,quiz:true},
  {subject:"네트워크",chapter:"응용계층",name:"DNS 동작원리",keywords:"계층구조·재귀/반복쿼리·캐싱",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"응용계층",name:"HTTP/HTTPS",keywords:"요청응답·메서드·상태코드·TLS",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"응용계층",name:"HTTP/2·HTTP/3",keywords:"멀티플렉싱·QUIC·헤더압축",freq:"중간",viz:false,quiz:true},
  {subject:"네트워크",chapter:"응용계층",name:"이메일 — SMTP·POP3·IMAP",keywords:"송수신프로토콜·차이점",freq:"낮음",viz:false,quiz:true},
  {subject:"네트워크",chapter:"네트워크 보안",name:"대칭키·공개키 암호화",keywords:"AES·RSA·키교환·디지털서명",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"네트워크 보안",name:"TLS/SSL·인증서",keywords:"핸드셰이크·CA·인증서체인",freq:"중간",viz:true,quiz:true},
  {subject:"네트워크",chapter:"네트워크 보안",name:"방화벽·IDS·IPS",keywords:"패킷필터링·상태검사·침입탐지",freq:"중간",viz:false,quiz:true},
  {subject:"네트워크",chapter:"네트워크 보안",name:"주요 공격유형",keywords:"DoS·DDoS·SQL인젝션·XSS·CSRF",freq:"높음",viz:false,quiz:true},
  // ══ 프로그래밍 언어론 ══
  {subject:"프로그래밍 언어론",chapter:"언어 패러다임",name:"명령형·절차적 프로그래밍",keywords:"변수·상태·순서·제어흐름",freq:"중간",viz:false,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"언어 패러다임",name:"객체지향 프로그래밍 (OOP)",keywords:"캡슐화·상속·다형성·추상화",freq:"높음",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"언어 패러다임",name:"함수형 프로그래밍",keywords:"순수함수·불변성·고차함수·람다",freq:"중간",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"언어 패러다임",name:"논리형·선언형 프로그래밍",keywords:"Prolog·SQL·특성",freq:"낮음",viz:false,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"타입 시스템",name:"정적·동적 타입",keywords:"컴파일타임·런타임·타입추론",freq:"중간",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"타입 시스템",name:"강타입·약타입",keywords:"암묵적변환·타입안전성",freq:"중간",viz:false,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"타입 시스템",name:"타입 다형성",keywords:"매개변수·서브타입·임시다형성",freq:"중간",viz:false,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"스코프·바인딩",name:"스코프 — 정적·동적",keywords:"어휘적범위·동적범위·클로저",freq:"중간",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"스코프·바인딩",name:"바인딩·수명",keywords:"정적/동적바인딩·변수수명",freq:"낮음",viz:false,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"실행 모델",name:"인터프리터·컴파일러 비교",keywords:"처리방식·JIT·바이트코드·VM",freq:"중간",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"실행 모델",name:"런타임 메모리 구조",keywords:"코드·데이터·힙·스택 세그먼트",freq:"높음",viz:true,quiz:true},
  {subject:"프로그래밍 언어론",chapter:"실행 모델",name:"활성레코드·콜스택",keywords:"함수호출·매개변수·지역변수·반환",freq:"중간",viz:true,quiz:true},
  // ══ 소프트웨어공학 ══
  {subject:"소프트웨어공학",chapter:"개발방법론",name:"소프트웨어 생명주기",keywords:"요구분석·설계·구현·테스팅·유지보수",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"개발방법론",name:"폭포수·나선형 모델",keywords:"순차적·위험분석·프로토타입",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"개발방법론",name:"애자일·스크럼",keywords:"스프린트·백로그·데일리스크럼·회고",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"개발방법론",name:"XP (익스트림 프로그래밍)",keywords:"TDD·페어프로그래밍·리팩토링·CI",freq:"낮음",viz:false,quiz:true},
  {subject:"소프트웨어공학",chapter:"요구공학",name:"요구사항 분류",keywords:"기능적·비기능적·사용자·시스템",freq:"중간",viz:false,quiz:true},
  {subject:"소프트웨어공학",chapter:"요구공학",name:"유스케이스·사용자스토리",keywords:"액터·유스케이스관계·스토리포인트",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"설계",name:"응집도·결합도",keywords:"높은응집·낮은결합·모듈화지표",freq:"높음",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"설계",name:"UML — 클래스다이어그램",keywords:"클래스·속성·메서드·관계",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"설계",name:"UML — 시퀀스·유스케이스다이어그램",keywords:"상호작용·시간순서·액터",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"설계",name:"디자인 패턴 — 생성",keywords:"싱글톤·팩토리·빌더·프로토타입",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"설계",name:"디자인 패턴 — 구조·행동",keywords:"어댑터·데코레이터·옵저버·전략",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"테스팅",name:"테스트 종류",keywords:"단위·통합·시스템·인수테스트",freq:"중간",viz:false,quiz:true},
  {subject:"소프트웨어공학",chapter:"테스팅",name:"화이트박스·블랙박스 테스트",keywords:"구문커버리지·경계값·동치분할",freq:"중간",viz:true,quiz:true},
  {subject:"소프트웨어공학",chapter:"테스팅",name:"TDD·회귀테스트",keywords:"테스트우선개발·자동화·CI/CD",freq:"중간",viz:false,quiz:true},
  {subject:"소프트웨어공학",chapter:"품질·유지보수",name:"소프트웨어 품질 속성",keywords:"ISO 25010·기능성·신뢰성·유지보수성",freq:"중간",viz:false,quiz:true},
  {subject:"소프트웨어공학",chapter:"품질·유지보수",name:"리팩토링·기술부채",keywords:"코드스멜·클린코드·지속개선",freq:"낮음",viz:false,quiz:true},
  // ══ 이산수학 ══
  {subject:"이산수학",chapter:"논리",name:"명제논리·술어논리",keywords:"논리연산자·동치·함의·증명",freq:"높음",viz:true,quiz:true},
  {subject:"이산수학",chapter:"논리",name:"증명 기법",keywords:"직접증명·귀류법·수학적귀납법",freq:"높음",viz:true,quiz:true},
  {subject:"이산수학",chapter:"집합·관계",name:"집합 연산",keywords:"합집합·교집합·차집합·멱집합·카테시안곱",freq:"높음",viz:true,quiz:true},
  {subject:"이산수학",chapter:"집합·관계",name:"관계의 성질",keywords:"반사·대칭·추이·동치관계·편순서",freq:"중간",viz:true,quiz:true},
  {subject:"이산수학",chapter:"집합·관계",name:"함수 유형",keywords:"단사·전사·전단사·역함수·합성함수",freq:"중간",viz:false,quiz:true},
  {subject:"이산수학",chapter:"조합론",name:"순열·조합·이항계수",keywords:"경우의수·파스칼삼각형·이항정리",freq:"높음",viz:true,quiz:true},
  {subject:"이산수학",chapter:"조합론",name:"비둘기집원리·포함배제",keywords:"최소최대보장·집합크기계산",freq:"중간",viz:false,quiz:true},
  {subject:"이산수학",chapter:"그래프이론",name:"그래프 기초 개념",keywords:"오일러·해밀턴 경로·회로·채색",freq:"중간",viz:true,quiz:true},
  {subject:"이산수학",chapter:"그래프이론",name:"트리·신장트리",keywords:"루트트리·신장트리·최소신장",freq:"중간",viz:true,quiz:true},
  {subject:"이산수학",chapter:"형식언어",name:"정규언어·유한오토마타",keywords:"DFA·NFA·정규표현식·클레이니",freq:"중간",viz:true,quiz:true},
  {subject:"이산수학",chapter:"형식언어",name:"문맥자유언어·푸시다운 오토마타",keywords:"CFG·파싱·BNF",freq:"중간",viz:false,quiz:true},
  // ══ 컴파일러 ══
  {subject:"컴파일러",chapter:"어휘분석",name:"어휘분석기 (Lexer)",keywords:"토큰·정규표현식·DFA·심볼테이블",freq:"중간",viz:true,quiz:true},
  {subject:"컴파일러",chapter:"구문분석",name:"파싱 — 하향식·상향식",keywords:"LL파서·LR파서·파스트리",freq:"중간",viz:true,quiz:true},
  {subject:"컴파일러",chapter:"구문분석",name:"CFG·BNF·EBNF",keywords:"문맥자유문법·유도·모호성",freq:"중간",viz:false,quiz:true},
  {subject:"컴파일러",chapter:"의미분석",name:"의미분석·타입검사",keywords:"타입규칙·심볼테이블·스코프분석",freq:"중간",viz:false,quiz:true},
  {subject:"컴파일러",chapter:"코드생성",name:"중간코드·코드최적화",keywords:"3주소코드·루프최적화·상수접기",freq:"낮음",viz:false,quiz:true},
  // ══ 자료구조 (추가) ══
  {subject:"자료구조",chapter:"균형 트리",name:"AVL 트리",keywords:"회전(LL/RR/LR/RL)·균형인수·높이균형",freq:"높음",viz:true,quiz:true},
  {subject:"자료구조",chapter:"균형 트리",name:"Red-Black 트리",keywords:"색규칙·삽입/삭제 재색칠·회전",freq:"높음",viz:false,quiz:true},
  {subject:"자료구조",chapter:"다방향 탐색트리",name:"B-트리·B+트리",keywords:"차수·분할·합병·순서집합인덱스",freq:"중간",viz:true,quiz:true},
  // ══ 알고리즘 (추가) ══
  {subject:"알고리즘",chapter:"정렬",name:"셸 정렬·기수 정렬",keywords:"간격수열·안정성·비교기반 외",freq:"중간",viz:false,quiz:true},
  {subject:"알고리즘",chapter:"최단경로",name:"다익스트라·벨만포드·플로이드",keywords:"음수간선·음수사이클·경로복원",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"최소신장트리",name:"크루스칼·프림 알고리즘",keywords:"Union-Find·우선순위큐·탐욕",freq:"높음",viz:true,quiz:true},
  {subject:"알고리즘",chapter:"그래프 심화",name:"위상정렬·강연결요소",keywords:"DAG·DFS기반·Kosaraju·Tarjan",freq:"중간",viz:true,quiz:true},
  // ══ 운영체제 (추가) ══
  {subject:"운영체제",chapter:"입출력 관리",name:"I/O 인터럽트·DMA",keywords:"폴링vs인터럽트·DMA제어기·채널",freq:"중간",viz:false,quiz:true},
  // 디스크 스케줄링은 기존 파일시스템 챕터에 이미 있음
  // ══ 컴퓨터 구조 (추가) ══
  {subject:"컴퓨터 구조",chapter:"논리회로",name:"부울 대수·게이트·카르노맵",keywords:"AND/OR/NOT/NAND/NOR/XOR·SOP/POS·간소화",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"논리회로",name:"조합논리회로·순서논리회로",keywords:"가산기·MUX/DEMUX·플립플롭·레지스터",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"명령어 구조",name:"RISC vs CISC·주소지정 방식",keywords:"명령어 형식·직접/간접/레지스터/즉시 주소",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨터 구조",chapter:"입출력 구조",name:"버스·인터럽트·DMA",keywords:"시스템버스·PCI·버스중재·데이지체인",freq:"중간",viz:false,quiz:true},
  // ══ 데이터베이스 (추가) ══
  {subject:"데이터베이스",chapter:"DBMS 개요",name:"DBMS 구조·3단계 스키마",keywords:"외부/개념/내부스키마·데이터독립성",freq:"중간",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"관계 대수",name:"관계 대수·관계 해석",keywords:"셀렉트·프로젝트·조인·나누기·투플해석",freq:"높음",viz:true,quiz:true},
  {subject:"데이터베이스",chapter:"회복 기법",name:"로그 기반 회복·체크포인트",keywords:"REDO·UNDO·즉시갱신·지연갱신·WAL",freq:"높음",viz:false,quiz:true},
  {subject:"데이터베이스",chapter:"인덱스",name:"인덱스·물리적 설계",keywords:"B+트리인덱스·해시인덱스·클러스터링",freq:"중간",viz:false,quiz:true},
  // ══ 네트워크 (추가) ══
  {subject:"네트워크",chapter:"흐름·혼잡제어",name:"슬라이딩 윈도우·Go-Back-N·SR",keywords:"윈도우크기·선택적재전송·혼잡윈도우",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"MAC·LAN",name:"이더넷·CSMA/CD·CSMA/CA",keywords:"충돌감지·충돌회피·토큰링·FDDI",freq:"중간",viz:true,quiz:true},
  {subject:"네트워크",chapter:"오류 제어",name:"오류 검출·수정 코드",keywords:"패리티·CRC·해밍코드·FEC vs ARQ",freq:"높음",viz:true,quiz:true},
  {subject:"네트워크",chapter:"IPv6·NAT",name:"IPv6 주소체계·NAT",keywords:"128비트·헤더구조·사설IP·포트변환",freq:"중간",viz:false,quiz:true},
  {subject:"네트워크",chapter:"네트워크 보안",name:"암호화·TLS·방화벽",keywords:"대칭/비대칭키·PKI·SSL/TLS·패킷필터링",freq:"중간",viz:false,quiz:true},
  // ══ 교육심리학 (추가) ══
  {subject:"교육심리학",chapter:"동기이론",name:"드웩 마인드셋",keywords:"고정·성장 마인드셋·귀인이론",freq:"중간",viz:false,quiz:true},
  // ══ 교육행정 (추가) ══
  {subject:"교육행정",chapter:"장학",name:"임상장학·동료장학·자기장학",keywords:"코간·골드해머·장학유형",freq:"중간",viz:false,quiz:true},
  // ══ 생활지도·상담 - 로저스는 기존 항목 있음(209번줄), 추가 불필요 ══
  // ══ 인공지능 ══
  {subject:"인공지능",chapter:"탐색",name:"맹목적 탐색 — BFS·DFS",keywords:"완전성·최적성·시간/공간복잡도",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"탐색",name:"정보기반 탐색 — A*",keywords:"휴리스틱·허용가능성·일관성",freq:"높음",viz:true,quiz:true},
  {subject:"인공지능",chapter:"탐색",name:"게임탐색 — 미니맥스·알파베타",keywords:"탐색트리·가지치기·게임이론",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"지식표현",name:"명제논리·술어논리 추론",keywords:"전향추론·후향추론·통일",freq:"낮음",viz:false,quiz:true},
  {subject:"인공지능",chapter:"머신러닝",name:"지도학습 — 분류·회귀",keywords:"의사결정트리·SVM·선형회귀",freq:"높음",viz:true,quiz:true},
  {subject:"인공지능",chapter:"머신러닝",name:"비지도학습 — 군집화",keywords:"K-means·계층적군집·차원축소",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"머신러닝",name:"과적합·정규화",keywords:"편향분산트레이드오프·L1·L2·드롭아웃",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"딥러닝기초",name:"신경망 기초",keywords:"퍼셉트론·활성화함수·역전파",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"딥러닝기초",name:"CNN·RNN 개념",keywords:"합성곱·풀링·순환구조·LSTM",freq:"중간",viz:true,quiz:true},
  {subject:"인공지능",chapter:"AI 윤리",name:"AI 편향·공정성",keywords:"데이터편향·알고리즘편향·공정성지표",freq:"높음",viz:false,quiz:true},
  {subject:"인공지능",chapter:"AI 윤리",name:"설명가능 AI (XAI)",keywords:"블랙박스문제·LIME·SHAP·투명성",freq:"중간",viz:false,quiz:true},
  // ══ 정보보안 ══
  {subject:"정보보안",chapter:"암호화",name:"대칭키 암호화",keywords:"AES·DES·블록암호·스트림암호",freq:"높음",viz:true,quiz:true},
  {subject:"정보보안",chapter:"암호화",name:"공개키 암호화",keywords:"RSA·ECC·키쌍·디지털서명",freq:"높음",viz:true,quiz:true},
  {subject:"정보보안",chapter:"암호화",name:"해시함수·MAC",keywords:"SHA·MD5·무결성·인증코드",freq:"높음",viz:true,quiz:true},
  {subject:"정보보안",chapter:"인증·접근제어",name:"인증 방식",keywords:"패스워드·OTP·생체인증·MFA",freq:"중간",viz:false,quiz:true},
  {subject:"정보보안",chapter:"인증·접근제어",name:"접근제어 모델",keywords:"DAC·MAC·RBAC·ABAC",freq:"중간",viz:true,quiz:true},
  {subject:"정보보안",chapter:"공격유형",name:"악성코드 유형",keywords:"바이러스·웜·트로이목마·랜섬웨어",freq:"중간",viz:false,quiz:true},
  {subject:"정보보안",chapter:"공격유형",name:"네트워크 공격",keywords:"DoS·DDoS·스니핑·스푸핑·MITM",freq:"높음",viz:false,quiz:true},
  {subject:"정보보안",chapter:"공격유형",name:"웹 취약점",keywords:"SQL인젝션·XSS·CSRF·SSRF",freq:"높음",viz:false,quiz:true},
  {subject:"정보보안",chapter:"보안 정책",name:"정보보안 관리체계",keywords:"ISMS·ISO27001·보안정책수립",freq:"중간",viz:false,quiz:true},
  // ══ CT ══
  {subject:"컴퓨팅 사고력(CT)",chapter:"CT 개념",name:"CT 정의·구성요소",keywords:"Wing·분해·패턴인식·추상화·알고리즘",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨팅 사고력(CT)",chapter:"CT 개념",name:"CT와 문제해결",keywords:"CT기반 문제해결과정·절차적사고",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨팅 사고력(CT)",chapter:"CT 교육",name:"CT 교육 접근법",keywords:"언플러그드·피지컬컴퓨팅·SW교육 연계",freq:"높음",viz:true,quiz:true},
  {subject:"컴퓨팅 사고력(CT)",chapter:"CT 교육",name:"CT 교육 수준별 적용",keywords:"초등·중등·고등 수준별 CT 교육 내용",freq:"중간",viz:false,quiz:true},
  {subject:"컴퓨팅 사고력(CT)",chapter:"CT 평가",name:"CT 평가 도구·루브릭",keywords:"Dr. Scratch·Bebras·관찰평가",freq:"중간",viz:true,quiz:true},
  // ══ 정보과 교육과정 ══
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"2022 개정 정보과 교육과정 구조",keywords:"핵심역량·영역구성·내용체계",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"정보과 핵심역량",keywords:"정보문화소양·CT·디지털소통·협력",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"정보과 내용체계 — 지식·이해",keywords:"개념·원리·이론 중심 내용",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"정보과 내용체계 — 과정·기능",keywords:"탐구·설계·구현·평가 역량",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"정보과 내용체계 — 가치·태도",keywords:"정보윤리·디지털시민성·공동체의식",freq:"중간",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"2022 개정",name:"고교학점제와 정보교과",keywords:"선택과목·공통정보·심화정보·AI기초",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"성취기준",name:"성취기준 분석·재구성",keywords:"성취기준 이해·교육과정재구성 방법",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"성취기준",name:"수업-평가 연계",keywords:"성취기준 기반 과정중심평가 설계",freq:"높음",viz:false,quiz:true},
  {subject:"정보과 교육과정",chapter:"교육과정 변천",name:"2015 개정 vs 2022 개정 비교",keywords:"내용변화·역량중심·SW교육의무화",freq:"중간",viz:true,quiz:true},
  // ══ 교수학습 방법 ══
  {subject:"교수학습 방법",chapter:"언플러그드",name:"언플러그드 활동 개념·원리",keywords:"컴퓨터 없는 CS교육·Bell 등",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"언플러그드",name:"언플러그드 활동 유형",keywords:"카드·보드게임·신체활동·역할극",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"언플러그드",name:"언플러그드 수업 설계",keywords:"CS개념 매핑·학년별 적용·평가",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습 방법",chapter:"피지컬 컴퓨팅",name:"피지컬 컴퓨팅 개념",keywords:"하드웨어·소프트웨어통합·센서·액추에이터",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"피지컬 컴퓨팅",name:"아두이노·마이크로비트",keywords:"주요기능·교육적활용·수업적용",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"피지컬 컴퓨팅",name:"피지컬컴퓨팅 수업 설계",keywords:"순서도→코딩→회로→테스트",freq:"중간",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"SW 교육",name:"블록코딩 — 스크래치·엔트리",keywords:"스프라이트·이벤트·순차·반복·조건",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"SW 교육",name:"텍스트코딩 — 파이썬 교육",keywords:"변수·함수·조건·반복·리스트",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"SW 교육",name:"블록→텍스트 전환 교수법",keywords:"단계적전환·동기부여·오류지도",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습 방법",chapter:"AI 교육",name:"AI 교육 도구 — 티처블머신",keywords:"이미지·소리·포즈 분류기 실습",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"AI 교육",name:"AI 교육 도구 — ML4Kids·엔트리AI",keywords:"데이터학습·모델훈련·연동",freq:"중간",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"AI 교육",name:"AI 개념 교육 내용",keywords:"데이터·특징·모델·학습·추론",freq:"높음",viz:true,quiz:true},
  {subject:"교수학습 방법",chapter:"PBL·프로젝트",name:"SW·AI 프로젝트 학습",keywords:"실제문제·설계·구현·발표·성찰",freq:"높음",viz:false,quiz:true},
  {subject:"교수학습 방법",chapter:"PBL·프로젝트",name:"팀기반 학습(TBL) 적용",keywords:"준비도검사·팀활동·동료평가",freq:"중간",viz:false,quiz:true},
  {subject:"교수학습 방법",chapter:"PBL·프로젝트",name:"디자인씽킹 적용",keywords:"공감·정의·아이디어·프로토타입·테스트",freq:"중간",viz:true,quiz:true},
  // ══ SW·AI 교육론 ══
  {subject:"SW·AI 교육론",chapter:"SW 교육 정책",name:"SW 교육 의무화 배경·정책",keywords:"디지털전환·2015~2022개정 흐름",freq:"중간",viz:false,quiz:true},
  {subject:"SW·AI 교육론",chapter:"SW 교육 정책",name:"정보교사 역할·전문성",keywords:"교육과정설계·테크놀로지활용·상담",freq:"중간",viz:false,quiz:true},
  {subject:"SW·AI 교육론",chapter:"AI 교육론",name:"AI 교육 내용체계",keywords:"인식·탐구·활용·설계·윤리 단계",freq:"높음",viz:true,quiz:true},
  {subject:"SW·AI 교육론",chapter:"AI 교육론",name:"AI 리터러시",keywords:"AI이해·비판적활용·창의적적용",freq:"높음",viz:false,quiz:true},
  {subject:"SW·AI 교육론",chapter:"디지털 시민성",name:"디지털 리터러시",keywords:"정보탐색·비판적이해·창의적생산",freq:"높음",viz:false,quiz:true},
  {subject:"SW·AI 교육론",chapter:"디지털 시민성",name:"AI·SW 윤리교육",keywords:"편향·프라이버시·저작권·디지털예절",freq:"높음",viz:false,quiz:true},
  {subject:"SW·AI 교육론",chapter:"디지털 시민성",name:"사이버폭력 예방교육",keywords:"유형·심리·예방·법적대응",freq:"중간",viz:false,quiz:true},
  // ══ 평가론 (정보교육) ══
  {subject:"평가론",chapter:"정보과 평가",name:"정보과 수행평가 설계",keywords:"산출물·포트폴리오·동료평가·루브릭",freq:"높음",viz:false,quiz:true},
  {subject:"평가론",chapter:"정보과 평가",name:"프로그래밍 과제 평가",keywords:"채점기준·자동채점·피드백방법",freq:"높음",viz:false,quiz:true},
  {subject:"평가론",chapter:"정보과 평가",name:"과정중심평가 실천",keywords:"관찰일지·체크리스트·포트폴리오",freq:"높음",viz:false,quiz:true},
  {subject:"평가론",chapter:"정보과 평가",name:"CT 평가 루브릭 개발",keywords:"CT구성요소별 수준기술·예시",freq:"중간",viz:true,quiz:true},
];
